# http:
#   routers:
#     restic-rtr:
#       rule: "Host(`example.com`)" 
#       entryPoints:
#         - websecure
#       middlewares:
#         - chain-no-auth
#       service: restic-svc
#   services:
#     restic-svc:
#       loadBalancer:
#         servers:
#           - url: "http://192.168.1.1:5555"
