[http.middlewares]

## Chains
[http.middlewares.chain-no-auth]
[http.middlewares.chain-no-auth.chain]
middlewares = ["middlewares-rate-limit", "middlewares-secure-headers"]

[http.middlewares.chain-basic-auth]
[http.middlewares.chain-basic-auth.chain]
middlewares = ["middlewares-rate-limit", "middlewares-secure-headers", "middlewares-basic-auth"]

## Basic Auth
[http.middlewares.middlewares-basic-auth]
[http.middlewares.middlewares-basic-auth.basicAuth]
realm = "Traefik2 Basic Auth" 
usersFile = "/shared/.htpasswd" # mount in docker-compose.yml



## Rate Limiting 
[http.middlewares.middlewares-rate-limit]
[http.middlewares.middlewares-rate-limit.rateLimit]
average = 100
burst = 50

## Secure Headers (see https://docs.traefik.io/middlewares/http/headers/)
[http.middlewares.middlewares-secure-headers]
[http.middlewares.middlewares-secure-headers.headers]
## HSTS  and XSS Filter
frameDeny = true #overwritten by customFrameOptionsValue
browserXssFilter = true 
# CORS (Cross-Origin Resource Sharing) headers
accessControlAllowMethods = ["GET", "OPTIONS", "PUT"]
accessControlMaxAge = 100
addvaryheader=true

forceSTSHeader = true
hostsProxyHeaders = ["X-Forwarded-Host"]
# sslRedirect = true
stsIncludeSubdomains = true
stsPreload = true
stsSeconds = 63072000
contentTypeNosniff = true 
# customFrameOptionsValue = "allow-from https:meln.ovh" #CSP takes care of this but may be needed for organizr. 
#      sslForceHost = true # add sslHost to all of the services
#      sslHost = "$DOMAINNAME"
referrerPolicy = "same-origin"
#      Setting contentSecurityPolicy is more secure but it can break things. Proper auth will reduce the risk.
#      the below line also breaks some apps due to 'none' - sonarr, radarr, etc.
#      contentSecurityPolicy = "frame-ancestors '*.$DOMAINNAME:*';object-src 'none';script-src 'none';"
PermissionsPolicy = "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
[http.middlewares.middlewares-secure-headers.headers.customResponseHeaders]
X-Robots-Tag = "none,noarchive,nosnippet,notranslate,noimageindex,"
server = ""
