[http]
[http.middlewares]
[http.middlewares.security.headers]
browserXssFilter = true
contentTypeNosniff = true
frameDeny = true
sslRedirect = true
#HSTS
stsIncludeSubdomains = true
stsPreload = true
stsSeconds = 31536000

[tls.options]
[tls.options.Aplus2021]
cipherSuites = [
  "TLS_CHACHA20_POLY1305_SHA256",
  "TLS_AES_128_GCM_SHA256",
  "TLS_AES_256_GCM_SHA384",
  "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
  "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
  "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
]
curvePreferences = [
  "CurveP521",
  "CurveP384",
]
minVersion = "VersionTLS12"
sniStrict = true
